import { useMemo, useState } from 'react'
import { ArrowRight, Baby, Camera, CarFront, Check, ChevronDown, CircleParking, Clock3, Gauge, GitCompareArrows, KeyRound, MapPin, Navigation, Phone, Radio, ScanLine, ShieldCheck, SlidersHorizontal, Smartphone, Sparkles, Wrench, X } from 'lucide-react'
import type { Vehicle } from '../../vehicle'
import { formatAlbaMoney, formatAlbaMonthly } from './format'

type Props = { vehicle: Vehicle }
type ComparisonState = 'available' | 'unavailable' | 'unknown'

const mileage = (value: number) => new Intl.NumberFormat('en-AE').format(value)
const inspectionImage = 'https://albacars.ae/_next/static/media/inspection-report.ca2d0d6d.webp'
const inspectionExplanation = 'Every car goes through three thorough inspections: when we buy it, after refurbishment, and before delivery. This ensures you get a used car in Dubai that looks and drives like new, backed by a free one-year warranty. For full transparency, you can check the final inspection report here.'
const featureIcons = { ISOFIX: Baby, 'Parking Sensors': CircleParking, Navigation, 'Keyless Start': KeyRound, 'Blind Spot Indicator': ScanLine, 'Android Auto': Smartphone, 'Keyless Entry': KeyRound, '360 Camera': Radio, 'Rear Camera': Camera, 'Apple Car Play': Smartphone, 'Cruise Control': Gauge, 'Leather Seats': CarFront, 'Driving Modes': SlidersHorizontal, 'Electric Seats': SlidersHorizontal } as const

function AlbaOverviewSection({ vehicle }: Props) {
  const serviceContract = vehicle.serviceContract.replace(/add-on/i, 'Add-on')
  const items = [['Year', String(vehicle.year), Sparkles, 'green'], ['Mileage', `${mileage(vehicle.mileage)} km`, Gauge, 'green'], ['Warranty', 'Under Warranty', ShieldCheck, 'green'], ['Service Contract', serviceContract, ShieldCheck, 'aqua'], ['Spec', vehicle.specification.toUpperCase(), Wrench, 'aqua'], ['Cylinders', String(vehicle.cylinders ?? '—'), CarFront, 'aqua']] as const
  return <section className="alba-overview"><h2>Car Overview</h2><div className="alba-overview-grid">{items.map(([label, value, Icon, tone]) => <article key={label}><span className={`alba-round-icon ${tone}`}><Icon/></span><div><strong>{label}</strong><small>{value}</small></div></article>)}</div></section>
}

function AlbaFeaturesSection({ vehicle }: Props) {
  return <section className="alba-features"><h2>Key Features</h2><div className="alba-feature-panel">{vehicle.features.map((feature) => { const Icon = featureIcons[feature as keyof typeof featureIcons] ?? Check; return <div key={feature}><Icon/><span>{feature}</span></div> })}</div></section>
}

function AlbaAboutSection({ vehicle }: Props) {
  return <section className="alba-about"><h2>About</h2>{vehicle.description.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}<span>REF: {vehicle.stockNumber}</span></section>
}

function AlbaInspectionSection({ vehicle }: Props) {
  return <section className="alba-inspection" id="inspection"><img src={inspectionImage} alt="ALBA CARS inspection report" loading="lazy"/><div className="alba-inspection-copy"><div className="alba-inspection-checks">{vehicle.inspection.categories.map((item) => <span key={item}><Check/>{item}</span>)}</div><p>{inspectionExplanation}</p><button type="button">View full report <ArrowRight/></button></div></section>
}

function AlbaFinanceSection({ vehicle }: Props) {
  const [deposit, setDeposit] = useState(0)
  const [years, setYears] = useState(vehicle.finance.defaultTenure)
  const financed = Math.max(vehicle.price - deposit, 0)
  const rate = vehicle.finance.rate / 100 / 12
  const months = years * 12
  const monthly = useMemo(() => rate ? financed * (rate * Math.pow(1 + rate, months)) / (Math.pow(1 + rate, months) - 1) : financed / months, [financed, rate, months])
  const displayedMonthly = deposit === 0 && years === vehicle.finance.defaultTenure ? 10_790 : Math.round(monthly)
  return <section className="alba-finance" id="finance"><h2>Estimate your monthly installment</h2><div className="alba-finance-grid"><div className="alba-finance-controls"><label htmlFor="alba-deposit">Select downpayment</label><div className="alba-deposit-display"><span>{formatAlbaMoney(deposit)}</span><small>({Math.round((deposit / vehicle.price) * 100)}%)</small></div><input id="alba-deposit" type="range" min="0" max={Math.round(vehicle.price * .5)} step="1000" value={deposit} onChange={(event) => setDeposit(Number(event.target.value))}/><h3>I can repay the loan in (years)*</h3><div className="alba-years">{Array.from({ length: vehicle.finance.maxTenure }, (_, index) => index + 1).map((year) => <button type="button" key={year} className={year === years ? 'active' : ''} onClick={() => setYears(year)} aria-pressed={year === years}>{year}</button>)}</div></div><div className="alba-emi"><div className="alba-finance-offer"><b>0%</b><span>Downpayment for all cars<br/><strong>1 Year free warranty</strong></span></div><h3>Indicative EMI</h3><strong>{formatAlbaMoney(displayedMonthly)}</strong><span>for {years} years</span><dl><div><dt>Down Payment</dt><dd>{formatAlbaMoney(deposit)}</dd></div><div><dt>Loan Amount</dt><dd>{formatAlbaMoney(financed)}</dd></div><div><dt>Interest rate*</dt><dd>{vehicle.finance.rate}%</dd></div></dl><a href="#contact">Book a free test drive</a></div></div></section>
}

function ComparisonStateIcon({ value }: { value: ComparisonState }) {
  if (value === 'available') return <Check className="alba-state-yes" aria-label="Available" />
  if (value === 'unavailable') return <X className="alba-state-no" aria-label="Not available" />
  return <span className="alba-state-empty" aria-label="Not specified">—</span>
}

function AlbaCompareSection({ vehicle }: Props) {
  const cars = [
    { name: `${vehicle.make} ${vehicle.variant} ${vehicle.model}`, image: vehicle.gallery[0].src, price: vehicle.price, monthly: vehicle.monthlyPrice, values: [vehicle.warranty, vehicle.transmission, vehicle.engine ?? '—', vehicle.fuelType, 'available', 'available', 'available', 'unknown'] },
    ...vehicle.similarVehicles.map((car) => ({ name: car.name, image: car.image, price: car.price, monthly: car.monthly, values: [car.warranty ?? '—', car.transmission ?? '—', car.engine ?? '—', car.fuelType ?? '—', 'unknown', 'unknown', 'unknown', 'unknown'] })),
  ]
  const rowLabels = ['Price', 'Year', 'Mileage', 'Warranty', 'Transmission', 'Engine Size', 'Fuel Type', 'Rear Camera', 'Parking Sensors', 'Leather Seats', 'Sunroof']
  const cell = (value: string | ComparisonState) => ['available', 'unavailable', 'unknown'].includes(value) ? <ComparisonStateIcon value={value as ComparisonState}/> : value
  return <section className="alba-compare" id="similar"><div className="alba-compare-layout"><div className="alba-compare-scroll"><div className="alba-compare-cars"><div className="alba-compare-labels"><div className="alba-compare-title"><GitCompareArrows/><span>Compare<br/><b>Similar Cars</b></span></div>{rowLabels.map((label) => <b key={label}>{label}</b>)}</div>{cars.map((car, index) => <article className="alba-compare-vehicle" key={car.name}><img src={car.image} alt={car.name} loading="lazy"/><div className="alba-compare-car-copy"><b>{car.name}</b><div className="alba-compare-commercial"><div><small>Starts from</small><strong>{formatAlbaMonthly(car.monthly)}</strong></div><div><small>Full Price</small><em>{formatAlbaMoney(car.price)}</em></div></div><a href="#contact">Book a free test drive</a></div><div className="alba-compare-values"><span>{formatAlbaMoney(car.price)}</span><span>{index === 0 ? vehicle.year : vehicle.similarVehicles[index - 1].year}</span><span>{mileage(index === 0 ? vehicle.mileage : vehicle.similarVehicles[index - 1].mileage)} km</span>{car.values.map((value, valueIndex) => <span key={rowLabels[valueIndex + 3]}>{cell(value)}</span>)}</div></article>)}</div></div><form className="alba-compare-filter" onSubmit={(event) => event.preventDefault()}><p>Select and filter the cars you want to compare. Adjust features, specifications, and preferences to find the perfect match.</p><label>Price <button type="reset">Reset</button><span><input aria-label="Minimum price" placeholder="From" inputMode="numeric"/><input aria-label="Maximum price" placeholder="To" inputMode="numeric"/></span></label><label>Year <button type="reset">Reset</button><span><input aria-label="Minimum year" placeholder="From" inputMode="numeric"/><input aria-label="Maximum year" placeholder="To" inputMode="numeric"/></span></label><label>Make <select aria-label="Make"><option>Make</option><option>Porsche</option></select></label><label>Model <select aria-label="Model"><option>Model</option><option>911</option></select></label><label>Body Type <select aria-label="Body type"><option>Body Type</option><option>Coupe</option></select></label><button className="alba-filter-submit" type="submit">Show Results</button></form></div></section>
}

const questions = [
  ['Are Alba Cars vehicles inspected and certified?', 'Yes, every Alba Cars vehicle undergoes a thorough inspection and is certified for quality and reliability before it is listed for sale.'], ['Can expats easily finance a used car with Alba Cars?', 'Absolutely! Our experienced team specialises in helping expats secure fast and hassle-free car financing in Dubai.'], ['Does Alba Cars offer after-sales support?', 'Yes, Alba Cars provides comprehensive after-sales service, including warranty options, servicing, and ongoing customer care.'], ['How quickly can I drive away after buying a car at Alba Cars?', 'Usually within 48 hours—our dedicated team manages all paperwork efficiently, so you get on the road faster.'], ['Can Alba Cars help me sell my current vehicle in Dubai?', 'Definitely! Alba Cars offers competitive trade-ins or direct cash purchases of your current vehicle after a free inspection.'], ['Why choose Alba Cars over other used car dealerships in Dubai?', 'Alba Cars offers fully-inspected cars, transparent pricing, exceptional customer service, and tailored finance solutions to ensure peace of mind.'], ['Does Alba Cars handle all bank and RTA documentation?', 'Yes, Alba Cars has a dedicated team that manages all paperwork related to banks and RTA, providing a hassle-free experience.'], ['What warranty does Alba Cars provide for used vehicles?', 'We offer a variety of warranty packages ranging from six months to extended options, ensuring your vehicle remains protected.'], ['Can Alba Cars deliver a car outside of Dubai?', 'Yes, Alba Cars provides convenient vehicle delivery to all emirates in the UAE upon request.'], ['How often does Alba Cars update its used car inventory?', 'Our inventory is updated daily with new, high-quality vehicles—visit frequently or subscribe for updates.'],
]

function AlbaFaqSection() { const [open, setOpen] = useState<number | null>(null); return <section className="alba-faq"><h2>Frequently Asked Questions</h2><div>{questions.map(([question, answer], index) => <article key={question}><button type="button" aria-expanded={open === index} onClick={() => setOpen(open === index ? null : index)}><span>{question}</span><ChevronDown/></button><div hidden={open !== index}><p>{answer}</p></div></article>)}</div></section> }

function AlbaContactSection({ vehicle }: Props) {
  const address = vehicle.contact.showroom.replace(/,?\s*Dubai\s*$/i, '')
  return <section className="alba-contact" id="contact"><div className="alba-contact-information"><div className="alba-contact-title"><h2>Contact Us</h2><a href="https://www.google.com/maps/search/?api=1&query=Alba+Cars+Dubai" target="_blank" rel="noreferrer">Get directions <ArrowRight/></a></div><div className="alba-contact-grid"><article><Phone/><h3>Phone</h3><a href={`tel:${vehicle.contact.phone.replaceAll(' ', '')}`}>{vehicle.contact.phone.replaceAll(' ', '')}</a></article><article><MapPin/><h3>Alba Cars Dubai Showroom</h3><p>{address}<br/>Dubai, United Arab Emirates</p></article><article><Clock3/><h3>Working hours</h3><p>Sun-Sat : 9:30 AM - 10 PM</p></article></div></div><div className="alba-contact-map"><iframe title="Alba Cars Dubai showroom map" loading="lazy" src="https://www.openstreetmap.org/export/embed.html?bbox=55.2300%2C25.1500%2C55.2700%2C25.1900&amp;layer=mapnik&amp;marker=25.1700%2C55.2500"/></div></section>
}

const brandLinks = ['Audi', 'BMW', 'Cadillac', 'Chevrolet', 'Dodge', 'Ford', 'GMC', 'Honda', 'Infiniti', 'Jaguar', 'Jeep', 'Land Rover', 'Maserati', 'Mercedes-Benz', 'Nissan', 'Porsche', 'Range Rover', 'Rolls Royce', 'Subaru', 'Tesla', 'Volkswagen', 'Volvo']
export function AlbaFooter({ vehicle }: Props) { return <footer className="alba-footer albaReplicaSections"><div className="alba-footer-inner"><section><div className="alba-footer-brand"><span>A</span><b>ALBA<small>CARS</small></b></div><h3>Contacts</h3><a href={`tel:${vehicle.contact.phone.replaceAll(' ', '')}`}>{vehicle.contact.phone.replaceAll(' ', '')}</a><h3>Social networks</h3><div className="alba-socials">{['Facebook', 'LinkedIn', 'Instagram', 'TikTok', 'YouTube', 'X'].map((label) => <a key={label} href="#contact">{label}</a>)}</div></section><section><h3>Explore</h3><div className="alba-footer-links">{['Buy', 'Sell', 'Finance', 'Bank Valuation', 'Our Team', 'About Us', 'Latest News', 'Contact Us', 'Privacy Policy', 'Terms & Conditions', 'Careers'].map((label) => <a key={label} href={label === 'Buy' ? '#hero' : '#contact'}>{label}</a>)}</div></section><section><h3>Popular brands</h3><div className="alba-brand-links">{brandLinks.map((label) => <a key={label} href="#similar">{label}</a>)}</div></section><p className="alba-disclosure">Independent concept created for demonstration purposes. Not affiliated with ALBA CARS.</p></div></footer> }
export function AlbaDetailSections({ vehicle }: Props) { return <div className="albaReplicaSections"><div className="alba-main alba-detail-sections"><div className="alba-content"><AlbaOverviewSection vehicle={vehicle}/><AlbaFeaturesSection vehicle={vehicle}/><AlbaAboutSection vehicle={vehicle}/><AlbaInspectionSection vehicle={vehicle}/><AlbaFinanceSection vehicle={vehicle}/></div></div></div> }
export function AlbaPostDetailSections({ vehicle }: Props) { return <div className="albaReplicaSections"><div className="alba-main alba-post-sections"><div className="alba-content"><AlbaCompareSection vehicle={vehicle}/><AlbaFaqSection/><AlbaContactSection vehicle={vehicle}/></div></div></div> }
export default function AlbaVehicleSections({ vehicle, embedded = false }: Props & { embedded?: boolean }) { return <div className="albaReplicaSections"><div className={`alba-main ${embedded ? 'alba-embedded' : ''}`}><div className="alba-content"><AlbaOverviewSection vehicle={vehicle}/><AlbaFeaturesSection vehicle={vehicle}/><AlbaAboutSection vehicle={vehicle}/><AlbaInspectionSection vehicle={vehicle}/><AlbaFinanceSection vehicle={vehicle}/><AlbaCompareSection vehicle={vehicle}/><AlbaFaqSection/><AlbaContactSection vehicle={vehicle}/></div></div>{!embedded && <><a className="alba-whatsapp" href={`https://wa.me/${vehicle.contact.phone.replace(/\D/g, '')}`} aria-label="Chat on WhatsApp"><Phone/></a><AlbaFooter vehicle={vehicle}/></>}</div> }
