import { useEffect, useRef, useState } from 'react'
import type { KeyboardEvent, PointerEvent } from 'react'
import { ChevronLeft, ChevronRight, RotateCcw, X } from 'lucide-react'
import type { GalleryImage } from '../vehicle'

type Props = { images: GalleryImage[]; initialIndex: number; trigger: HTMLElement | null; restoreFocus: boolean; onClose: () => void }
const clamp = (value: number, min: number, max: number) => Math.min(Math.max(value, min), max)

export default function GalleryLightbox({ images, initialIndex, trigger, restoreFocus, onClose }: Props) {
  const [index, setIndex] = useState(initialIndex); const [zoomed, setZoomed] = useState(false)
  const dialogRef = useRef<HTMLDivElement>(null); const imageRef = useRef<HTMLImageElement>(null); const stageRef = useRef<HTMLElement>(null)
  const points = useRef(new Map<number, { x: number; y: number }>()); const gesture = useRef({ x: 0, y: 0, distance: 0, zoom: 1, panX: 0, panY: 0 }); const startX = useRef(0)
  const move = (delta: number) => setIndex((value) => (value + delta + images.length) % images.length)
  const apply = () => { const image = imageRef.current; const stage = stageRef.current; if (!image || !stage) return; const data = gesture.current; const box = stage.getBoundingClientRect(); const maxX = box.width * (data.zoom - 1) * .42; const maxY = box.height * (data.zoom - 1) * .34; data.panX = clamp(data.panX, -maxX, maxX); data.panY = clamp(data.panY, -maxY, maxY); image.style.transform = `translate3d(${data.panX}px,${data.panY}px,0) scale(${data.zoom})` }
  const reset = () => { gesture.current.zoom = 1; gesture.current.panX = 0; gesture.current.panY = 0; apply(); setZoomed(false) }
  useEffect(() => { const old = document.body.style.overflow; document.body.style.overflow = 'hidden'; dialogRef.current?.focus(); return () => { document.body.style.overflow = old; if (restoreFocus) trigger?.focus({ preventScroll: true }) } }, [restoreFocus, trigger])
  useEffect(() => { gesture.current.zoom = 1; gesture.current.panX = 0; gesture.current.panY = 0; if (imageRef.current) imageRef.current.style.transform = 'translate3d(0,0,0) scale(1)'; setZoomed(false) }, [index])
  const keyDown = (event: KeyboardEvent<HTMLDivElement>) => { if (event.key === 'Escape') { event.preventDefault(); event.stopPropagation(); onClose() } else if (event.key === 'ArrowLeft') { event.preventDefault(); event.stopPropagation(); move(-1) } else if (event.key === 'ArrowRight') { event.preventDefault(); event.stopPropagation(); move(1) } else if (event.key === 'Tab') { const nodes = Array.from(dialogRef.current?.querySelectorAll<HTMLElement>('button:not([disabled]),[tabindex]:not([tabindex="-1"])') ?? []); if (nodes.length && !event.shiftKey && document.activeElement === nodes[nodes.length - 1]) { event.preventDefault(); nodes[0].focus() } } }
  const down = (event: PointerEvent<HTMLElement>) => { event.currentTarget.setPointerCapture(event.pointerId); points.current.set(event.pointerId, { x: event.clientX, y: event.clientY }); if (points.current.size === 1) { gesture.current.x = event.clientX; gesture.current.y = event.clientY; startX.current = event.clientX } else { const [a, b] = Array.from(points.current.values()); gesture.current.distance = Math.hypot(b.x - a.x, b.y - a.y) } }
  const drag = (event: PointerEvent<HTMLElement>) => { if (!points.current.has(event.pointerId)) return; points.current.set(event.pointerId, { x: event.clientX, y: event.clientY }); const data = gesture.current; if (points.current.size >= 2) { const [a, b] = Array.from(points.current.values()); const distance = Math.hypot(b.x - a.x, b.y - a.y); data.zoom = clamp(data.zoom * distance / Math.max(data.distance, 1), 1, 2.8); data.distance = distance; apply(); setZoomed(data.zoom > 1.01) } else { const point = Array.from(points.current.values())[0]; if (data.zoom > 1.01) { data.panX += point.x - data.x; data.panY += point.y - data.y; apply() } data.x = point.x; data.y = point.y } }
  const end = (event: PointerEvent<HTMLElement>) => { const point = points.current.get(event.pointerId); points.current.delete(event.pointerId); try { event.currentTarget.releasePointerCapture(event.pointerId) } catch { /* capture was released */ } if (point && gesture.current.zoom <= 1.01 && points.current.size === 0 && Math.abs(point.x - startX.current) > 42) move(point.x > startX.current ? -1 : 1) }
  const stopStageGesture = (event: PointerEvent<HTMLButtonElement>) => event.stopPropagation()
  return <div className="lightbox-overlay" role="presentation"><div className="lightbox-dialog" role="dialog" aria-modal="true" aria-label="Vehicle photo lightbox" ref={dialogRef} tabIndex={-1} onKeyDown={keyDown}><header><span>{String(index + 1).padStart(2, '0')} / {String(images.length).padStart(2, '0')}</span><button onClick={onClose} aria-label="Close full screen photo"><X size={20}/><span>Close</span></button></header><main ref={stageRef} onPointerDown={down} onPointerMove={drag} onPointerUp={end} onPointerCancel={end} onDoubleClick={reset}><img ref={imageRef} src={images[index].src} alt={images[index].alt} draggable={false}/>{zoomed && <button className="lightbox-reset" onPointerDown={stopStageGesture} onClick={reset}><RotateCcw size={16}/> Reset</button>}<button className="lightbox-arrow previous" onPointerDown={stopStageGesture} onClick={() => move(-1)} aria-label="Previous photo"><ChevronLeft/></button><button className="lightbox-arrow next" onPointerDown={stopStageGesture} onClick={() => move(1)} aria-label="Next photo"><ChevronRight/></button></main></div></div>
}
